spring:
  profiles:
    active: local
---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:online_bank
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8080
<script>

#demo for git stash command

//BUG 121 fixing going on...
function HandlerDemo(){
	let a = 43+ 45;
	//work in progrss.....
}



#Now Handling BUG122 due to priority 

function add(){
    let x = 12;
    let y = 45;
    let z = x + y;
    console.log("Outtput:"+z);
}

</script>

